[project]
name = "brollm"
version = "0.1.1"
description = "When you think about light weight LLMs, call brollm!"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.39.17",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
